name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Install goreleaser
        run: |
          curl -fsSL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh
      - name: Run goreleaser
        run: |
          goreleaser release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
